### ISSUE TITLE
Consider adding floating point precision tolerance 

### ISSUE THREAD

**Issue by hoyosjs** [vu-cs3251-f16/assignment5-2#1]

**Comment by sxlijin** [comment]
Do you mean [this](https://github.com/vu-cs3251-f16/assignment5-2/blob/master/tests/testHelper.h#L16-L18)?...

**Comment by ghemingway** [comment]
Two students have said to me that their simulations run for many time steps but eventually diverge from the correct answers.  One student was using a different version of G (grav. constant) and probably something else.  Math is math, things should not run with random values in this program.
